### ISSUE TITLE
bug when use it in avs 2.6

### ISSUE THREAD

**Issue by realfinder** [HomeOfAviSynthPlusEvolution/neo_FFT3D#3]
colorbars()
converttoyv12
Spline36Resize(880,496) #or any resizer
neo_FFT3D
info

will give https://user-images.githubusercontent.com/2512153/83254119-e701dc00-a1b6-11ea-9b6a-3bc55d98b92f.png

same as https://github.com/Asd-g/AviSynth-vsTTempSmooth/issues/2 and https://github.com/Asd-g/AviSynth-vsMSharpen/issues/2

**Comment by msg7086** [comment]
[msvc-x64/neo-fft3d.zip](https://github.com/HomeOfAviSynthPlusEvolution/neo_FFT3D/files/4871293/neo-fft3d.zip)

Can you check if this is any better?

**Comment by realfinder** [comment]
there are no avs 2.6 in x64, only avs+ has x64

**Comment by msg7086** [comment]
[neo-fft3d.zip](https://github.com/HomeOfAviSynthPlusEvolution/neo_FFT3D/files/4872940/neo-fft3d.zip)

x86

**Comment by realfinder** [comment]
yes, that work, thanks

**Comment by msg7086** [comment]
Ah, OK, I'll release it soon.
