### ISSUE TITLE
AVX512 don't correct

### ISSUE THREAD

**Issue by kedaitinh12** [HomeOfAviSynthPlusEvolution/neo_FFT3D#7]
In the present, Xinyue Lu still don't fix it, maybe Asd-g can fix it???
https://forum.doom9.org/showthread.php?p=1911088#post1911088

**Comment by kedaitinh12** [comment]
After fixed, maybe can you add opt = 0 Auto detect with AVX512 enabled again

**Comment by kedaitinh12** [comment]
Thanks

**Comment by kedaitinh12** [comment]
But opt=0 still disable avx512

**Comment by Asd-g** [comment]
AVX512 doesn't give additional speed here from quick test. It could be a bit slower in some cases compared to AVX because usually works at lower CPU freq.

**Comment by kedaitinh12** [comment]
Thanks for explain
